### ISSUE TITLE
[Epic] [Enabler] [GDG] Support GDG and special characters.

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#1366]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Enabler description

This epic is in place to track the work needed to support GDS (Generation Data Sets) within a GDG (Generation Data Group) as well as special character support for data sets. 

## GDG and GDS
A Generation Data Group (GDG) is a catalog entry used to maintain a group of Generation Data Sets (GDS).

### Relative
The epic should deliver the ability for users to be able to use GDS as they would any other module `src` that accesses a data set. Support for GDS can be relative or absolute. 

Relative naming follows syntax GDG(n), where:
n = 0 for the current GDS
n = -1 for the previous GDS
n = +1 for a new GDS

For example, using syntax such as `ANSIBLE.DATA.GDS(0)` is the current version, `ANSIBLE.DATA.GDS(-1)`for prior generations and for new `ANSIBLE.DATA.GDS(+1)`.

### Absolute
The generation and version number are in the form GxxxxVyy, where xxxx is an unsigned four-digit decimal generation number (0001 - 9999) and yy is an unsigned two-digit decimal version number (00 - 99). 

For example:
 A.B.C.G0001V00 is generation data set 1, version 0, in generation data group A.B.C.
 A.B.C.G0009V01 is generation data set 9, version 1, in generation data group A.B.C.

When a relative generation number is used, the operating system assigns an absolute generation number and a version number of V00 to represent the relative generation name. The absolute generation number assigned depends on the number last assigned and the value of the relative generation number that you are now specifying. 

For example, if in a previous job generation, A.B.C.G0006V00 was the last generation, and you specify A.B.C(+1), the generation now cataloged is assigned the number G0007V00.

Any positive relative generation number can be used, a number greater than 1 can cause absolute generation numbers to be skipped for a new generation data set. For example, if you have a single step job and the generation being cataloged is a +2, one generation number is skipped.

For more information on GDG, see [reference section 4.3.6 Generation Data Group](file:///Users/ddimatos/Downloads/abcs-of-ibm-z-os-system-programming-volume-3.pdf) and image below:
<img width="574" alt="image" src="https://github.com/ansible-collections/ibm_zos_core/assets/25803172/81345072-ccc0-40a6-9703-593bc033ff1e">

## Special Characters in Data Sets
This epic should also deliver the ability to manage special characters in data set naming without the need for a user to escape the special character, an escape would violate the permitted char allowed for a data set name, eg `\$` should not be allowed from users, while the underlying code may be escaping, it is not something that should come from a user. 

The special characters to be supported are ` (only #, @, or $), or a hyphen (-)` in any data set name or member name, there are conventions when they can be used, please review[ data set naming rules documentation](https://www.ibm.com/docs/en/engineering-lifecycle-management-suite/lifecycle-management/7.0.2?topic=definitions-zos-data-set-naming-rules). 

Note the rules such as:
```
The first segment character must be either a letter or one of the following three special characters: #, @, $.
The remaining seven characters in a segment can be letters, numbers, special characters (only #, @, or $), or a hyphen (-).
```
## General design
While this is still under review, the principle behind supporting GDS will be that all modules will use the absolute GDS name, users will be able to use either relative or absolute names but the modules will ONLY use the absolute name. 

While still being discussed, the design being currently favored is that the betterArgParser would return a dictionary would return both the, relative and absolute name, the importance of having both names is so that if a the module must communicate with the user, it should do so using the name originally provided to the module, eg relative GDS. 

Similar in design is the special character support where the dictionary would provide the original name and an escaped version for use by the module. 

It is also possible betterArgParser could be renamed to something like zosArgParser().

There are a number of collections using the betterArgParser, this should be communicated early so they have ample time to adjust. 

## Testing
This will require a number of new test cases be added to validate both GDG/GDS and special characters. 

## Issues
Work identified for either GDG/GDS or Special Characters or both are listed below

- [x] 1. [Enabler] [zos_archive] GDG/GDS and special character support #1367
- [x] 2. [Enabler] [zos_backup_restore] GDG/GDS and special character support #1368
- [x] 3. [Enabler] [zos_blockinfile] GDG/GDS and special character support #1369 
- [x] 4. [Enabler] [zos_copy] GDG/GDS and special character support #1370
- [x] 5. [Enabler] [zos_data_set] GDG/GDS and special character support #1371
- [x] 6. [Enabler] [zos_encode] GDG/GDS and special character support #1372
- [x] 7. [Enabler] [zos_fetch] GDG/GDS and special character support #1373
- [ ] 8. [Enabler] [zos_find] GDG/GDS and special character support #1374
- [x] 9. [Enabler] [zos_job_submit] GDG/GDS and special character support #1375
- [x] 10. [Enabler] [zos_lineinfile] GDG/GDS and special character support #1376
- [x] 11. [Enabler] [zos_mvs_raw] GDG/GDS and special character support #1377
- [ ] 12. [Enabler] [zos_mount] GDG/GDS and special character support #1378 
- [x] 13. [Enabler] [zos_tso_command] GDG/GDS and special character support #1379 
- [x] 14. [Enabler] [zos_apf] Special character support #1380
- [x] 15. [Enabler] [zos_unarchive] Special character support #1381 
- [x] 16. [Enabler] [bettterArgParser] GDG/GDS and special character support #1382 
- [x] 17. [Enabler] [module_utils/data_set.py] GDG/GDS support #1386 

## Unaffected modules

No development for these modules but that will automatically included as part of regression. 
1. zos_script
2. zos_gather_facts
3. zos_job_output
4. zos_job_query
5. zos_operator
6. zos_operator_action_query
7. zos_ping
8. zos_volume_init

## Notes
Relates to ZOAU tracker NAZARE-9618

## Special Character Issues

[[Bug] [zos_data_set] Not able to create data sets with names that include permitted symbols](https://github.com/ansible-collections/ibm_zos_core/issues/642) #642
[[Bug] [zos_job_submit] unable to submit member that contain $](https://github.com/ansible-collections/ibm_zos_core/issues/724) #724
[[Bug] zos_job_submit interprets $ #1011](https://github.com/ansible-collections/ibm_zos_core/issues/1011)
