### ISSUE TITLE
[Collaboration] [Epic] [zos_backup_restore] Support keywords - ADMINISTRATOR, BYPASSACS, MGMTCLAS, NULLMGMTCLAS, RENAME, RENAMEUNCONDITIONAL, REPLACE, REPLACEUNCONDITIONAL, SHARE, SPHERE, STORCLAS, NULLSTORCLAS, TOLERATE(ENQFAILURE)

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#1530]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Support and service?

- [X] Yes, support and service is involved.
- [ ] No, support and service is involved.

### Collaboration description

Enhancement is to support additional keywords for zos_backup_restore module.
This is part of EPIC #1180.
Attached is the prototype PDF and zip (doc and examples only, no source changes).
Also attached will be the patch of the module so you can apply it to the module and reuse it.
[zos_backup_restore_protoptype.pdf](https://github.com/user-attachments/files/15745879/zos_backup_restore.Backup.and.restore.data.sets.and.volumes.IBM.z_OS.core.collection.1.0.0.documentation.pdf)

[backup.zip](https://github.com/user-attachments/files/15745880/backup.zip)

Git patch for source and RST, you can path your branch with `git apply the.patch`.
[doc_diff_for_zos_backup_restore.py.patch](https://github.com/user-attachments/files/15745946/doc_diff_for_zos_backup_restore.py.patch)
[doc_diff_for_zos_backup_restore.rst.patch](https://github.com/user-attachments/files/15745947/doc_diff_for_zos_backup_restore.rst.patch)

This results in new options, `output`, `index` , `sms`, `access`.

| Keyword               | Status  | Issue |
| --------------------- | ------- | ----- |
| [ADMINISTRATOR](https://github.com/ansible-collections/ibm_zos_core/issues/1180#administrator) | proposed | #1538 |
| [BYPASSACS](https://github.com/ansible-collections/ibm_zos_core/issues/1180#bypassacs) | proposed | #1537 |
| [MGMTCLAS](https://github.com/ansible-collections/ibm_zos_core/issues/1180#mgmtclas) | implemented | #1537 |
| [NULLMGMTCLAS](https://github.com/ansible-collections/ibm_zos_core/issues/1180#nullmgmtclas) | proposed | #1537 |
| [NULLSTORCLAS](https://github.com/ansible-collections/ibm_zos_core/issues/1180#nullstorclas) | proposed | #1537 |
| [RENAME*](https://github.com/ansible-collections/ibm_zos_core/issues/1180#rename)  | proposed |  #1536 |
| [RENAMEUNCONDITIONAL](https://github.com/ansible-collections/ibm_zos_core/issues/1180#renameunconditional)  | proposed |  #1536 |
| [REPLACE*](https://github.com/ansible-collections/ibm_zos_core/issues/1180#replace)  | rejected |  #1536 |
| [REPLACEUNCONDITIONAL*](https://github.com/ansible-collections/ibm_zos_core/issues/1180#replaceuncoditional)  | proposed |  #1536 |
| [SHARE](https://github.com/ansible-collections/ibm_zos_core/issues/1180#share) | proposed |  #1538 |
| [SPHERE](https://github.com/ansible-collections/ibm_zos_core/issues/1180#shere) | proposed |  #1539 |
| [STORCLAS](https://github.com/ansible-collections/ibm_zos_core/issues/1180#storeclas) | implemented |  #1537 |
| [TOLERATE(ENQFAILURE)](https://github.com/ansible-collections/ibm_zos_core/issues/1180#tolerate) | implemented | #1180 |

*Not part of the collaboration, brought in by the developer to expand on the modules experience as a whole.

### IBM z/OS Ansible core Version

v1.9.0 (default)

### IBM Z Open Automation Utilities

v1.2.5 (default)

### IBM Enterprise Python

v3.11.x (default)

### ansible-version

v2.16.x (default)

### z/OS version

v2.5 (default)

### Ansible module

zos_backup_restore
