### ISSUE TITLE
[Enabler][Z Trial] (3) Scenario ALL - Get the dev box set up

### ISSUE THREAD

**Issue by fernandofloresg** [ansible-collections/ibm_zos_core#1577]
This task is a part of epic: #1523 

### Enabler description
As a user I want to have more current versions of dependencies like ZOAU 1.3+, Python 3.12+ & ibm_zos_core version 1.10+ available such that the experience I had during Z Trial transfers more directly into versions of components available for my own environment.

### Tasks:

- [ ] add updated version of `ansible-core`
- [ ] add updated version of `open enterprise sdk for python` (pyz)
- [ ] add updated version of `ZOAU`
- [ ] set up ketan/Marcel with the appropriate tooling and login credentials

NOTE- do not update any playbook files in this item.

**Comment by richp405** [comment]
Base box up and validated Fri/2 August.  Updating software and testing m/f connection today.

**Comment by richp405** [comment]
Here is good and bad:
Good - it can work
Bad - it will be nowhere near new versions:
..... cygwin (I'll see if the sig's are still active) - doesn't support Python > 3.9
..... ansible is stuck at 2.9.13
.... python install of ansible gets hung up on a missing wheel or rust compiler
.... EVEN SO, the current/old demo works, and the "mainframe" is responding fine.

![Image](https://github.com/user-attachments/assets/6df8f646-919f-45fe-9b35-5166eb583877)

For this week, I'll get the new tiles set up for the change of content, then will research upgrading... I have python 3.12 of the main demo system... this is a limitation of cygwin.

**Comment by richp405** [comment]
Ran a backup on Friday, will do a start/load/test run today.

**Comment by richp405** [comment]
Dev box is updated.  Ansible 2.15, python 3.9, and zos_core 1.10... working on zvm next, to update python and zoau there.
