### ISSUE TITLE
[Epic][Enabler][AC] Update the AC tool used by the development team with additional requirements

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#1628]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Enabler description

This epic is in place to manage the various AC tooling work, whether an enhancement or change, the goal is to use this epic to put focus on the development of the tool to bring it to completion since its taking on a bigger role in our development flow. 

- [ ] [[Enabler] [AC] Consider updating it to use `zInventory-raw` vs `zInventory` which uses a file instead of a string](https://github.com/ansible-collections/ibm_zos_core/issues/1607)
- [ ] [[Enabler] [AC , ./profile.sh] Add support for zSH on z/OS for AC](https://github.com/ansible-collections/ibm_zos_core/issues/1609)
- [ ] [[Enabler] [AC] Add return code capabilities to other AC options](https://github.com/ansible-collections/ibm_zos_core/issues/1608)
