### ISSUE TITLE
[Enabler] [Epic] [zos_job_query] Performance evaluation and issue related tasks.

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#1841]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Enabler description

This epic will contain a number of issues related to `zos_job_query` , while some of the issues are bug fixes or issues waiting on dependencies from ZOAU, collectively these issues should address the performance concerns of the module raised in issue #1606 , see [comment](https://github.com/ansible-collections/ibm_zos_core/issues/1606#issuecomment-2524214791).

- [ ] (1) [Enabler] [zos_job_query] Profile/measure the modules performance #1840
- [x] (2) [Bug] [zos_job_query] Appears to use a wildcard when a job_id is used. #1839 
- [x] (3) [Bug] [zos_job_query] Subsystem not in return values #1694

There could be a 4th issue, it is not created because it depends mostly on what issue (1) returns but also how much more performant the module is after bullets 2 and 3. This 4th issue would only be needed when the module gets the `program_name` from ZOAU and it performs poorly then we would want to offer an option to disable getting it to improve the performance. Since we currently return it, it would make sense to leave that behavior and offer an option to return an empty string (no call to get program_name) making it a users decision to not have it returned. 

These two issues are not currently owned by this epic, but are indirectly related:
- zos_job_query getting BGYSC5308E Failed to serialize JSON object #1764 
- [Enhancement] Allow a fast and flexible method for querying jobs on the spool #1606
   - I would leave #1606 open until the epic here completes with positive results, once it does then #1606 can be cancelled as this issue was requesting a dynamic response to improve performance, it has been explained that would not yield improved numbers because the values come back in one SSI 80 call now as it is, where this epic is about improving performance.
