### ISSUE TITLE
[Task] [CI/CD] [Research] Explore the option to use an IBM Cloud z/OS Virtual Server Instance (zVSI)

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#438]
### Task description

With the ability to now run zVSI it would be good if we researched how this could be leveraged by our pipelines. 

This research should return answers to:
- [ ] Knowledge transfer to the team how one creates the zVSI, including but not limited to creating an account. 
- [ ] Cost determination - what is our expected financial obligation to keep an image running for a month
- [ ] Scope what it will take to run our regression fully on a zVSI - i expect this to be a reasonable amount of work to do so.
- [ ] Configuration and any other knowledge sharing to connect it and run our regression on the test
