### ISSUE TITLE
[Enhancement] [Epic] [zos_copy] Preserve American Standards Association (ASA) text file control characters

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#835]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Ansible module

zos_copy

### Enhancement or feature description

This issue represents all work needing to be completed to ensure ASA support. Some of the items in the list below could be considered no longer needed or cancelled as development and testing progresses.

[ASA control characters](https://www.ibm.com/docs/en/zos/2.5.0?topic=output-using-asa-text-files) are ' ' (blank), '+', '-', and '0 thru '9', and 'A' thru 'C' one-byte field at the beginning of each record for data sets allocated with an `A` as in VBA and FBA.

1. [x] Research ASA, generate, inspect and ensure reproduction such that a test can can be created.
     - #883 
3. [x] Evaluate existing support for ASA in commands and programs.
     - #884 
5. [x] Evaluate `zos_copy` capabilities when interacting with ASA.
     - #885
7. [ ] Propose and deliver solution, for example maybe a new option such as `asa_text`.
     - #886 

Documents:
1) https://en.wikipedia.org/wiki/ASA_carriage_control_characters
2) https://www.ibm.com/docs/en/zos/2.4.0?topic=descriptions-cp-copy-file
3) https://www.ibm.com/docs/en/zos/2.5.0?topic=output-using-asa-text-files
4) https://www.ibm.com/docs/en/zos/2.5.0?topic=sets-control-characters
