### ISSUE TITLE
[Module][Epic][zos_stat] - ablity to stat z/OS resources

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#882]
### Is there an existing issue for this?

- [X] There are no existing issues.

### New module description

Description:
`zos_stat` should have parity to the community [stat module](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/stat_module.html), meaning the interfaces should to some extent be alike. 

Depending the research of the item, we may want to scope the name out to `zos_stat` or `zos_mvs_stat` to not identify with the community stat module and set expectations that there is overlap in that the module can also stat USS (UNIX System Services files). 

Research should also include testing the community `stat` module on USS and ensuring is functional to the community expectations. There are going to be some differences, for example tags, apf bits, and other extended attributes that are specific to USS at which may  or may not show up in the community module. Thus we may need to also overlap with the stat module on USS and remain with the name `zos_stat`.

The general idea of the zos_stat module is to return users data set statistics such volume, organization type, record length, in catalog, etc. Much of this we have from the LISTDS , LISTCAT and VTOC parsing we do but its not nearly complete as it could be. 

**Epic Issues:**

- [x] [Module][zos_stat] evaluate the sources the module will drive #1004 
- [x] [Module][zos_stat] evaluate the sources the module will drive #1006 
- [x] [Module][Epic][zos_stat] prototype an interface #1005

Suggestions:
- In this research we should look at what we have today, what we could do with REXX and/or C in ZOAU. 
- I would recommend reaching out to DFSMS for added suggestions. 
- Performing a minimal search I did come across the [RMM LISTDATASET](https://www.ibm.com/docs/en/zos/2.3.0?topic=subcommands-listdataset-displaying-information-about-data-set) command I have never tried before, its worth looking into it as well by DFSMS
   - Under the DFSMSrmm command there are man other LIST* that seem interesting, but this could require Security class READ access. 
- There are also the [XLC C/C++ runtime libs](https://www.ibm.com/docs/en/zos/2.2.0?topic=functions-stat-get-file-information) which would not be for Ansible necessarily but worth discussing with ZOAU.
- It might be worth discussing this with Mike Fulton as well.
- See also [listds](https://www.ibm.com/docs/en/zos/2.4.0?topic=subcommands-listds-command)
- See also [listcat](https://www.ibm.com/docs/en/zos/2.4.0?topic=subcommands-listcat-command)
- Sea also [Dcollect](https://www.ibm.com/docs/en/zos/2.1.0?topic=output-dcollect-record-structure)
- The collections module_utils has many methods running `listds`, `listcat` and a vtoc utility as well that could be of help.
- Onno would also be a good focal to review this research. 
- See below for some of my REXX snippets which may need additional work to run.

Snippets:
```
# cat listdsi.rexx
/*REXX*/
ADDRESS ISPEXEC
X = LISTDSI("'"ANSIBLE.COBOL.LOADLIB3"'")
SAY 'DSNAME =    ' SYSDSNAME
SAY 'LRECL  =    ' SYSLRECL
SAY 'BLKSIZE =   ' SYSBLKSIZE
SAY ' USED       ' SYSUNITS '= ' SYSUSED
SAY ' ALLOCATED  ' SYSUNITS '= ' SYSALLOC
```

```
/* REXX*/
 x = LISTDSI('''ANSIBLE.COBOL.LOADLIB3''' MULTIVOL)
 SAY 'Function code from LISTDSI is: '  x
      say 'LISTDSI Function Code is : ' x
      say 'LISTDSI Reason Code is   : ' sysreason
         SAY 'FUNCTION CODE FROM LISTDSI IS: ' X
dsinfo=LISTDSI(FILE_NAME)
X = LISTDSI("'"ANSIBLE.COBOL.LOADLIB3"'")
```

```
/* rexx */
X=listdsi("'ANSIBLE.COBOL.LOADLIB3'" "")
say 'DSN:' SYSDSNAME
exit
```

To start the research, here is a list of zos_data_set options described in the prototype but also you can see these [here](https://www.ibm.com/docs/en/zos/2.1.0?topic=rfstab-data-set-creation-attributes):
• blks
• cyls
• recs
• trks
• blksize
• data class
• directory of space
• dsntype
• keys
• lrecl
• management clase
• model
• recfm
• record_size
• rlse
• norlse
• share options
• spanned
• nonspanned
• space (primary, aux)
• storage class
• unit
• volume
