### ISSUE TITLE
[Epic] [Enabler] Adopt and support ZOAU 1.3 API changes

### ISSUE THREAD

**Issue by storfibm** [ansible-collections/ibm_zos_core#931]
### Enabler description

ZOAU is moving towards a new VR. This release includes some changes that are incompatible with 1.2. With the adoption of ZOAU 1.3, the z/OS Core Collection will require adjustments to fully function with ZOAU version 1.3. This will raise the minimum ZOAU version to 1.3 for IBM z/OS Core version 1.10.0-beta.1.

This epic outlines the various modules, utils and test cases affected by the API changes, each git issue will outline recommended changes, there could be more which regression testing should identify. Additionally, as each module is being reviewed, this is an opportune time to improve code readability; consider variable renaming and adding additional comments for clarity.

It is imperative that the issues for this epic be coordinated without overlap, this will ease the migration and avoid merge issues. Starting such a coordinate effort should begin by:

1. Ensure there are no carry over pull requests pending in the development branch from Q4 2023, complete all PRs and ensure all are merged into `dev` this provides our baseline for collection version 1.10-beta.1.
2. Create a feature branch from `dev` (e.g. `module-utils-migration`) where all module utility issues will be addressed and later merged into `dev`
3. Following the module utility updates, modules will be carefully planned to avoid overlapping changes, beginning with ones with the least number of dependencies.

Each module can be impacted by one of these API changes:
- Impacted by ZOAU Dataset API
- Impacted by ZOAU jobs API
- Impacted by the rename of types.py to ztypes.py
- Impacted by the contents of module volumes.py having been moved to datasets.py
- Impacted by opercmd timeout to milli seconds
- Impacted by JSON schema change in either apfadm, dmod, dsed or zinfo
- Impacted by Exceptions schema

#### Module test cases needing dependency reduction Git issues:
- [x] [[Enabler] Remove zos_copy dependency from zos_archive test cases to aid in ZOAU 1.3 migration](https://github.com/ansible-collections/ibm_zos_core/issues/1129)
- [x] [[Enabler] Remove zos_copy dependency from zos_blockinfile test cases to aid in ZOAU 1.3 migration](https://github.com/ansible-collections/ibm_zos_core/issues/1130)
- [x] [[Enabler] Remove zos_copy dependency from zos_encode test cases to aid in ZOAU 1.3 migration](https://github.com/ansible-collections/ibm_zos_core/issues/1131)
- [x] [[Enabler] Remove zos_blockinfile dependency from zos_fetch test cases to aid in ZOAU 1.3 migration](https://github.com/ansible-collections/ibm_zos_core/issues/1132)
- [x] [[Enabler] Remove zos_copy dependency from zos_fetch test cases to aid in ZOAU 1.3 migration](https://github.com/ansible-collections/ibm_zos_core/issues/1133)
- [x] [[Enabler] Remove zos_encode dependency from zos_lineinfile test cases to aid in ZOAU 1.3 migration](https://github.com/ansible-collections/ibm_zos_core/issues/1134)
- [x] [[Enabler] Remove zos_copy dependency from zos_lineinfile test cases to aid in ZOAU 1.3 migration](https://github.com/ansible-collections/ibm_zos_core/issues/1135)
- [x] [[Enabler] Remove zos_fetch dependency from zos_copy test cases to aid in ZOAU 1.3 migration](https://github.com/ansible-collections/ibm_zos_core/issues/1147)

#### Module utility Git issues:
- [x]  [[Enabler] [Dev] [module_utils/backup.py] Migrate module, module utilities and test cases to ZOAU 1.3](https://github.com/ansible-collections/ibm_zos_core/issues/1115)
- [x]  [[Enabler] [Val] [module_utils/better_arg_parser.py] Migrate module, module utilities and test cases to ZOAU 1.3](https://github.com/ansible-collections/ibm_zos_core/issues/1116)
- [x]  [[Enabler] [Dev] [module_utils/copy.py] Migrate module, module utilities and test cases to ZOAU 1.3](https://github.com/ansible-collections/ibm_zos_core/issues/1117)
- [x]  [[Enabler] [Dev] [module_utils/data_set.py] Migrate module, module utilities and test cases to ZOAU 1.3](https://github.com/ansible-collections/ibm_zos_core/issues/1118)
- [x]  [[Enabler] [Dev] [module_utils/dd_statement.py] Migrate module, module utilities and test cases to ZOAU 1.3](https://github.com/ansible-collections/ibm_zos_core/issues/1119)
- [x]  [[Enabler] [Dev] [module_utils/encode.py] Migrate module, module utilities and test cases to ZOAU 1.3](https://github.com/ansible-collections/ibm_zos_core/issues/1120)
- [x]  [[Enabler] [Dev] [module_utils/job.py] Migrate module, module utilities and test cases to ZOAU 1.3](https://github.com/ansible-collections/ibm_zos_core/issues/1121)

#### Module Git Issues involving migration:
- [x] [[Enabler] [Dev] [zos_apf] Migrate module, module utilities and test cases to ZOAU 1.3](https://github.com/ansible-collections/ibm_zos_core/issues/1102)
- [x] [[Enabler] [Dev] [zos_archive] Migrate module, module utilities and test cases to ZOAU 1.3](https://github.com/ansible-collections/ibm_zos_core/issues/1103)
- [x] [[Enabler] [Dev] [zos_backup_restore] Migrate module, module utilities and test cases to ZOAU 1.3](https://github.com/ansible-collections/ibm_zos_core/issues/1104)
- [x] [[Enabler] [Dev] [zos_blockinfile] Migrate module, module utilities and test cases to ZOAU 1.3](https://github.com/ansible-collections/ibm_zos_core/issues/1105)
- [x] [[Enabler] [Dev] [ zos_copy] Migrate module, module utilities and test cases to ZOAU 1.3](https://github.com/ansible-collections/ibm_zos_core/issues/1106)
- [x] [[Enabler] [Dev] [zos_encode] Migrate module, module utilities and test cases to ZOAU 1.3](https://github.com/ansible-collections/ibm_zos_core/issues/1107)
- [x] [[Enabler] [Dev] [zos_fetch] Migrate module, module utilities and test cases to ZOAU 1.3](https://github.com/ansible-collections/ibm_zos_core/issues/1108)
- [x]  [[Enabler] [Dev] [zos_gather_facts] Migrate module, module utilities and test cases to ZOAU 1.3](https://github.com/ansible-collections/ibm_zos_core/issues/1109)
- [x]  [[Enabler] [Dev] [zos_job_submit] Migrate module, module utilities and test cases to ZOAU 1.3](https://github.com/ansible-collections/ibm_zos_core/issues/1110)
- [x]  [[Enabler] [Dev] [zos_lineinfile] Migrate module, module utilities and test cases to ZOAU 1.3](https://github.com/ansible-collections/ibm_zos_core/issues/1111)
- [x]  [[Enabler] [Dev] [zos_operator] Migrate module, module utilities and test cases to ZOAU 1.3](https://github.com/ansible-collections/ibm_zos_core/issues/1112)
- [x]  [[Enabler] [Dev] [zos_operator_action_query] Migrate module, module utilities and test cases to ZOAU 1.3](https://github.com/ansible-collections/ibm_zos_core/issues/1113)
- [x]  [[Enabler] [Dev] [zos_unarchive] Migrate module, module utilities and test cases to ZOAU 1.3](https://github.com/ansible-collections/ibm_zos_core/issues/1114)

#### Module Git Issues involving only validation:
- [x] [[Enabler] [Val] [zos_job_output] Validate module with ZOAU 1.3](https://github.com/ansible-collections/ibm_zos_core/issues/1137)
- [x] [[Enabler] [Val] [zos_tso_command] Validate module with ZOAU 1.3](https://github.com/ansible-collections/ibm_zos_core/issues/1138)
- [x] [[Enabler] [Val] [zos_ping] Validate module with ZOAU 1.3](https://github.com/ansible-collections/ibm_zos_core/issues/1139)
- [x] [[Enabler] [Val] [zos_mvs_raw] Validate module with ZOAU 1.3](https://github.com/ansible-collections/ibm_zos_core/issues/1140)
- [x] [[Enabler] [Val] [zos_job_query] Validate module with ZOAU 1.3](https://github.com/ansible-collections/ibm_zos_core/issues/1141)
- [x] [[Enabler] [Val] [zos_find] Validate module with ZOAU 1.3](https://github.com/ansible-collections/ibm_zos_core/issues/1142)
- [x] [[Enabler] [Val] [zos_mount] Validate module with ZOAU 1.3](https://github.com/ansible-collections/ibm_zos_core/issues/1143)
- [x] [[Enabler] [Val] [zos_volume_init] Validate module with ZOAU 1.3](https://github.com/ansible-collections/ibm_zos_core/issues/1144)
- [x] [[Enabler] [Val] [zos_data_set] Validate module with ZOAU 1.3](https://github.com/ansible-collections/ibm_zos_core/issues/1145)
- [x] [[Enabler] [Val] [zos_script] Validate module with ZOAU 1.3](https://github.com/ansible-collections/ibm_zos_core/issues/1146)

#### Regression (tests) Git issues requiring migration:
- [x]  [[Enabler] [tests/test_zos_data_set_func.py] Migrate module, module utilities and test cases to ZOAU 1.3](https://github.com/ansible-collections/ibm_zos_core/issues/1124)
- [x]  [[Enabler] [tests/test_zos_gather_facts.py] Migrate module, module utilities and test cases to ZOAU 1.3](https://github.com/ansible-collections/ibm_zos_core/issues/1126)
- [x]  [[Enabler] [tests/test_zos_mount_func.py] Migrate module, module utilities and test cases to ZOAU 1.3](https://github.com/ansible-collections/ibm_zos_core/issues/1127)

#### Test case dependency count (see bottom for more details):

| Test case                             |  No. depen | Dependencies before module reduction                  | Dependencies after module reduction             |
|---------------------------------------|------------|-------------------------------------------------------|-------------------------------------------------|
| test_zos_operator_func.py | 0 |none|none|
| test_zos_ping_func.py | 0 |none|none|
| test_zos_tso_command_func.py | 0  |none|none|
| test_zos_apf_func.py | 0 |none|none|
| test_zos_gather_facts_func.py | 0 |none |none|
| test_zos_job_submit_func.py | 1 |zos_data_set|zos_data_set|
| test_zos_mvs_raw_func.py | 1 |zos_data_set|zos_data_set|
| test_zos_backup_restore.py | 1 |zos_data_set|zos_data_set|
| test_zos_job_output_func.py | 1 |zos_job_submit|zos_job_submit|
| test_zos_script_func.py | 1 |zos_copy|zos_copy|
| test_zos_operator_action_query_func.py | 1 |zos_operator|zos_operator|
| test_zos_archive_func.py | 2 |zos_data_set,zos_copy|zos_data_set|
| test_zos_volume_init_func.py | 2 |zos_data_set,zos_operator|zos_data_set,zos_operator|
| test_zos_mount_func.py | 2 |zos_copy, zos_data_set|zos_copy, zos_data_se|
| test_zos_find_func.py | 2 |zos_lineinfile, zos_data_set|zos_lineinfile, zos_data_set|
| test_zos_job_query_func.py | 2 |zos_data_set, zos_job_submit|zos_data_set, zos_job_submit|
| test_zos_encode_func.py | 3 |zos_data_set,zos_job_submit,zos_copy|zos_data_set,zos_job_submit|
| test_zos_blockinfile_func.py | 3 |zos_data_set, zos_copy, zos_encode|zos_data_set, zos_encode|
| test_zos_data_set_func.py | 3 |zos_job_submit,zos_job_output,zos_copy|zos_job_submit,zos_job_output,zos_copy|
| test_module_security.py | 3 |zos_data_set, zos_job_submit, zos_job_output|zos_data_set, zos_job_submit, zos_job_output|
| test_zos_lineinfile_func.py | 3 |zos_data_set, zos_copy, zos_encode|zos_data_set|
| test_zos_unarchive_func.py | 3 |zos_archive, zos_data_set, zos_fetch|zos_archive, zos_data_set, zos_fetch|
| test_zos_fetch_func.py | 5 |zos_job_submit, zos_copy, zos_encode, zos_data_set, zos_blockinfile|zos_job_submit, zos_encode, zos_data_set|
| test_zos_copy_func.py | 5 |zos_data_set, zos_mvs_raw, zos_encode, zos_job_submit, zos_fetch|zos_data_set, zos_mvs_raw, zos_encode, zos_job_submit|

#### Additional context
-ZOAU 1.3 migration guide: https://www.ibm.com/docs/en/zoau/1.3.x?topic=planning-migrating-zoau-v13-from-v12x-earlier
-Python levels established by ZOAU 1.3
| Python version |  APAR   |   PTF   |
| -------------- | ------- | ------- |
| 3.9.16            | PH55814 | UI92787 |
| 3.10.12           | PH55866 | UI92802 |
| 3.11.4           | PH55880 | UI92806 |
| 3.12           | Any     | Any     |

#### Exceptions in 1.2.x:
```
class ZOAUException(Exception): Y
class DatasetVerificationError(Exception): N
class JobSubmitException(Exception): Y
class JobPurgeException(Exception): N
class MissingEnvironmentVariable(Exception): N
class DDQueryException(Exception):
```

#### Exceptions in 1.3:
General Exceptions:
```
_ZOAUExtendableException(Exception): 
  - Custom exception supporting a string message and ZOAUResponse object (new exception)  
 
ZOAUException(_ZOAUExtendableException):
  - Errors happening during ZOAU core calls, see message for details
```

Dataset exceptions:
```
DatasetFetchException(_ZOAUExtendableException):
- Errors during dataset queries, see message for details (new exception)  
 
DatasetFormatException(_ZOAUExtendableException):
- Dataset content does not match expected formats, see message for details (new exception)  
 
DatasetWriteException(_ZOAUExtendableException):
- Errors while trying to write into a Dataset, see message for details (new exception)  

DatasetVerificationError(Exception):
```

Job exceptions:
```
JobFetchException(_ZOAUExtendableException):
- Errors during job fetch, see message for details (new exception)  

JobSubmitException(_ZOAUExtendableException): 
- Job submission errors, see message for details

JobCancelException(_ZOAUExtendableException): 
- Job cancelling errors, see message for details (new exception)  
 
JobPurgeException(_ZOAUExtendableException):
- Job purging errors, see message for details

DDQueryException(_ZOAUExtendableException): 
- Errors during a Job's DD Querying, see message for details
```

Non ZOAUResponse Exceptions:
```
JobCancelConfirmException(Exception):
- Cannot confirm job cancellation, see message for details (new exception)  

JobPurgeConfirmException(Exception): 
- Cannot confirm purge of given job, see message for details (new exception)  
```

Miscellaneous Exceptions:
```
class MissingEnvironmentVariable(Exception)
class MissingFunctionParameter(Exception) (new exception)  
```

**Comment by ddimatos** [comment]
This work item was overlooked but the majority of the team is aware and including it in the current tasks that involve the zoau 1.3 migration, this issue was put on hold till the 1.3 work since we will be editing nearly every module, its a good time to include this change, it should be nominal, copy/paste in the imports. 
https://github.com/ansible-collections/ibm_zos_core/issues/1087

**Comment by ddimatos** [comment]
Congratulations team, you delivered 2 weeks early !!!!
