### ISSUE TITLE
[Collaboration] Deprecation warnings from ansible-core regarding UTF-8 support

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#983]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Support and service?

- [ ] Yes, support and service is involved.
- [X] No, support and service is involved.

### Are the dependencies a supported?

- [ ] Yes, the dependencies are supported.
- [X] Not applicable to this collaboration.

### IBM Z Open Automation Utilities

None

### IBM z/OS Ansible core Version

None

### ansible-version

v2.14.x

### z/OS version

None

### Collaboration description

This is a collaboration effort for the IBM Ansible Z team to try to understand the deprecation warnings we are seeing under various conditions. Although outside the scope of the teams mission, it is critical enough to divert time to understand if the problem is arising from the `ibm_zos_core` collection or something the team can deliver to the `ansible-core` community.

This collaboration should include issues thus there is no need to size this collaboration. 

The issues should focus:

- [x] Understanding the `ansible-core` code changes historically meaning find the commits and PRs associated to this change. See #984 
- [x] Does the warning (even though it can be disabled) break a playbooks execution. See #985 
- [x] Determine which modules are impacted (maybe not every module), have a good understanding which `ibm_zos_core` modules are impacted and if some of the community modules are impacted. See #986
- [x] Propose a solution either for `ibm_zos_core` or one for `ansible-core` or a work around that does not interrupt playbook execution. See #987
- [x] Implement the solution. See #988

**Comment by ddimatos** [comment]
This warning has appeared in issues:
https://github.com/ansible-collections/ibm_zos_core/issues/737
https://github.com/ansible-collections/ibm_zos_core/issues/775
